ami_id="ami-059d836af932792c3"
instance_type="t2.micro"
region="us-east-2"
ssh_conection_name="demo-rules"
ssh_conection_ingress=[
    {
        from_port=22
        to_port=22
        protocol="tcp"
        cidr_blocks=["0.0.0.0/0"]
    },
    {
        from_port=80
        to_port=80
        protocol="tcp"
        cidr_blocks=["0.0.0.0/0"]
    }
]
